config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  get '/welcome' => 'root#welcome', as: :welcome
  get '/login' => 'root#login'
  get '/new' => 'root#new'
  get '/snap' => 'root#snap_login', as: :snap

  resources :user_sessions, only: [:new, :create, :destroy] do
    collection do
      get 'log_out'
    end
  end

  resources :snap_logins, only: [:update, :show, :destroy]

  get '/saml/auth' => 'saml_idp#new'
  get '/saml/metadata' => 'saml_idp#show'
  post '/saml/auth' => 'saml_idp#create'

  get '/saml/snap' => 'saml_idp#snap', as: :saml_snap

  resources :devices, only: [:destroy] do
    collection do
      get :enroll
    end
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  include RootHelper

  def new
    #put enrollment of new users here
  end

  def login
    # render the login page
    redirect_to welcome_url and return if current_user
    token = cookies.signed[:snap_login]
    if token.present?
      @snap_login = SnapLogin.find_by_token(token)
    end
    if @snap_login.nil?
      @snap_login = SnapLogin.new
      @snap_login.token = UUIDTools::UUID.random_create.to_s
      enroll_url = snap_login_url(@snap_login)
      if enroll_url.include?('localhost')
        enroll_url = request.protocol + local_ip + ':' + request.port.to_s + snap_login_path(@snap_login)
      end
      @snap_login.url = enroll_url
      @snap_login.save
      cookies.signed[:snap_login] = @snap_login.token
    end
    @user_session = UserSession.new
  end

  def index
    # redirect_to welcome_url and return if current_user
    # token = cookies.signed[:snap_login]
    # if token.present?
    #   @snap_login = SnapLogin.find_by_token(token)
    # end
    # if @snap_login.nil?
    #   @snap_login = SnapLogin.new
    #   @snap_login.token = UUIDTools::UUID.random_create.to_s
    #   @snap_login.save
    #   cookies.signed[:snap_login] = @snap_login.token
    # end
    # if @snap_login && @snap_login.email.present?
    #   @user_session = UserSession.create(User.find_by_email(@snap_login.email), true)
    #   @snap_login.destroy
    #   cookies.delete :snap_login
    #   redirect_to welcome_url
    # else
    #   @user_session = UserSession.new
    # end
  end

  def snap_login
    token = cookies.signed[:snap_login]
    snap_login = token.present? && SnapLogin.find_by_token(token)
    cookies.delete :snap_login
    if snap_login
      snap_login.destroy
      if snap_login.snapped
        device = Device.find_by_public_key snap_login.public_key
        if device && device.user
          UserSession.create(device.user, true)
          redirect_to welcome_url
          return
        end
      end
    end
    redirect_to login_path
  end

  def welcome
    render 'not_logged_in' unless current_user
    token = cookies.signed[:snap_login]
    if token.present?
      @snap_login = SnapLogin.find_by_token(token)
    end
    if @snap_login.nil?
      @snap_login = SnapLogin.new
      @snap_login.token = UUIDTools::UUID.random_create.to_s
      enroll_url = snap_login_url(@snap_login)
      if enroll_url.include?('localhost')
        enroll_url = request.protocol + local_ip + ':' + request.port.to_s + snap_login_path(@snap_login)
      end

      @snap_login.url = enroll_url
      @snap_login.save
      cookies.signed[:snap_login] = @snap_login.token
    end
  end

end

app/helpers/root_helper.rb
module RootHelper

  def local_ip
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true
    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end
end

app/views/root/index.html.erb
<% if current_user_session %>
    <h2>Welcome <%= current_user.name %></h2>
    <%=	button_to 'Log out', '/user_sessions/log_out', method: :get  %>
<% else %>
    <%= form_for @user_session do |f| %>
        <% if @user_session.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user_session.errors.count, 'error') %> prohibited:</h2>
              <ul>
                <% @user_session.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <%= f.label :email %><br />
        <%= f.text_field :email %><br />
        <br />
        <%= f.label :password %><br />
        <%= f.password_field :password %><br />
        <br />
        <%= f.submit 'Login' %>
    <% end %>
    <%=	 form_for @snap_login do |f| %>
        <input type="hidden" id="full_url" value="<%= request.protocol + @local_ip + ':' + request.port.to_s + snap_login_path(@snap_login) %>"/>
        <input type="hidden" id="same_origin_url" value="<%= snap_login_url(@snap_login) %>"/>
        <%= f.label :token %>
        <%=	f.text_field :token %>
        <br />
        <%= f.label :email %>
        <%= f.text_field :email %>
        <br />
        <%= f.submit 'Login' %>
    <% end %>
    <p>Or use your smartphone to scan this code</p>
    <div id="qrcode">
        <div id="code"></div>
        <p data-bind="text: url()"></p>
        <p data-bind="text: 'auth challenge: ' + challenge()"></p>
        <button data-bind="click: regenerate"> refresh challenge</button>
    </div>
<% end %>

app/views/root/index.slim
.container
  .jumbotron
    = image_tag 'snaplogin.png', class: 'snap-login-logo-index'
    .row
      h1 Smartphone + SAML <small>A 2 day experiment </small>
      p Using SAML and a smartphone we log in to SAML enabled apps.  An integration using SAML & Dropbox is implemented.  Log in to the Snap Login enrollment page using the snap login icon below.
      p <small> This site and the integration is based on a 2 day hackathon by the SafeNet Labs team. </small>
  .row
    h2.text-center style='margin-bottom: 30px' Apps
    .select-app-panel
      .col-sm-2
        a href='#{login_path}' =image_tag 'snapicon.png', class: 'snap-login-image'
      .col-sm-2
        a href='https://www.dropbox.com/sso/184229534' =image_tag 'db_logo_blue@2x.png', class: 'snap-login-image'

app/views/root/login.slim
.container
  = render partial: 'root/partials/requesting_title'
  .row
    .col-sm-4
      h2 Login with username and password
      = form_for @user_session do |f|
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
        = f.submit 'Login', class: 'btn btn-default'
    input type="hidden" id="full_url" value=@snap_login.url
    input type="hidden" id="check_url" value=snap_login_path(@snap_login)
    input type="hidden" id="redirect_url" value=snap_path
    =render partial: 'root/partials/smartphone_option'
    =render partial: 'root/partials/google_maps'

app/views/root/not_logged_in.slim
p you are not logged in

app/views/root/welcome.html.slim
.container
  .row
    h1 Welcome #{current_user.name}
  .row style='margin-top: 30px;'
    .col-sm-6
      .col-sm-6
        p Use your phone to log in from now on. Open Snap Login on your phone and point it at the code on the right
      .col-sm-6
        = image_tag 'iphone.png', style: 'height: 400px'
    .col-sm-6
      - if @snap_login
        input type="hidden" id="full_url" value=@snap_login.url
        input type="hidden" id="check_url" value=snap_login_path(@snap_login)
        input type="hidden" id="redirect_url" value=enroll_devices_url

        #qrcode
          #code
          /p data-bind="text: url()"
          /p data-bind="text: 'auth challenge: ' + challenge_url"
          /= button_to 'Refresh Challenge', snap_login_path(@snap_login), method: :delete
          button.btn.btn-default data-bind="click: regenerate" Refresh
  .row
    h2 Enrolled Devices
    ul.list-unstyled
      - if current_user.devices.count == 0
        li You have no enrolled devices
      - else
        - current_user.devices.each do |device|
          li #{device.name} #{button_to 'Forget', device_path(device), method: :delete, class: 'btn btn-default'}
  .row style='margin-top: 30px;'
    = button_to 'Log out', log_out_user_sessions_path, method: :get, class: 'btn btn-default'